# Generated by Django 5.0.2 on 2024-03-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_expensecategory_expense_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensecategory',
            old_name='name',
            new_name='categories',
        ),
    ]
