# Generated by Django 5.0.2 on 2024-03-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_expense_expense_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.expensecategory'),
        ),
    ]
